### ISSUE TITLE
Meta exists, while reviews are absent

### ISSUE THREAD

**Issue by yegor256** [iakunin/codexia-bot#67] opened 2020-04-21 05:13 UTC
Take a look: https://www.codexia.org/p/774

I see meta information stored about Reddit and HN, but no reviews posted. Is it a bug?

**Comment by iakunin** [comment] 2020-04-21 06:14
@yegor256 this happens due to daily review limits for bots.

These reviews are in the db-queue now and will be sent as soon as limits will expire.

See the db-queue screenshot:
![image](https://user-images.githubusercontent.com/10430347/79831293-cc666700-83af-11ea-8653-a03665d881f3.png)

Each review in queue correlates with the corresponding meta:
![image](https://user-images.githubusercontent.com/10430347/79831345-e99b3580-83af-11ea-9048-ff3b64379900.png)


To prevent such a case from happening, in my opinion, we should increase the review limits for bot (maybe just only for my bot) as I described in [this codexia-issue](https://github.com/yegor256/codexia/issues/106).

@yegor256 what do you think?

**Comment by iakunin** [comment] 2020-04-25 14:32
@yegor256 since this is not a bug, I'd prefer to close this issue.

**Closed by iakunin** 2020-04-25 14:32 UTC
